# encodings_file: "face_encodings.pkl"
# database: "tracking.db"
# camera_floors:
#   0: "Floor 1"
#   1: "Floor 2"
#   2: "Floor 3"
# debounce_seconds: 5
# evidence_dir: "evidence"
# process_every_n_frames: 10 

encodings_file: "face_encodings.pkl"
database: "tracking.db"
debounce_seconds: 5
evidence_dir: "evidence"
process_every_n_frames: 10

# Map RTSP URLs to their corresponding camera names
camera_floors:
  "rtsp://admin:Admin123@192.168.0.100:554/Streaming/Channels/101": "Finance Room"
  "rtsp://admin:Admin123@192.168.0.100:554/Streaming/Channels/201": "AI Room"
  "rtsp://admin:Admin123@192.168.0.100:554/Streaming/Channels/302": "Outdoor"
  "rtsp://admin:Admin123@192.168.0.100:554/Streaming/Channels/402": "Meeting Room"
  "rtsp://admin:Admin123@192.168.0.100:554/Streaming/Channels/502": "Corridor"
  "rtsp://admin:Admin123@192.168.0.100:554/Streaming/Channels/602": "Reception"
  "rtsp://admin:Admin123@192.168.0.100:554/Streaming/Channels/702": "Ops Room"
  # "rtsp://admin:UNIface360@192.168.1.168:554/Streaming/Channels/301": "Finance Room"
  # "rtsp://admin:UNIface360@192.168.1.168:554/Streaming/Channels/401": "AI Room"